stream_over_http_enabled: true
server:
  http_listen_port: 3200
  log_level: info
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
ingester:
  max_block_bytes: 1048576
  max_block_duration: 5m
  flush_check_period: 1m
  flush_blocks_on_shutdown: true
compactor:
  compaction:
    block_retention: 24h
storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks

