apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../serve
images:
  - name: ghcr.io/aurelius-in/edgesight-qa
    newName: ghcr.io/aurelius-in/edgesight-qa
    digest: sha256:REPLACE_PROD