image:
  repository: ghcr.io/your-org
  tag: latest
  pullPolicy: IfNotPresent

resources: {}

env:
  CAMERA_URL: file:/app/assets/sample.mp4
  CONF_THRESHOLD: "0.5"
  MQTT_BROKER: mosquitto
  MQTT_PORT: "1883"


