version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
  capture:
    build: ../../services/capture
    environment:
      - PREPROCESS_URL=http://preprocess:9002/frame
      - FRAME_RATE_CAP=5
      - CAMERA_URL=file:/app/assets/sample.mp4
      - FRAME_WIDTH=640
      - FRAME_HEIGHT=360
    ports: ["9001:9001"]
    depends_on:
      - preprocess
    volumes:
      - ../../assets:/app/assets:ro
  preprocess:
    build: ../../services/preprocess
    environment:
      - INFERENCE_URL=http://inference:9003/infer
      - FRAME_WIDTH=640
      - FRAME_HEIGHT=360
    ports: ["9002:9002"]
    depends_on:
      - inference
  inference:
    build: ../../services/inference
    environment:
      - MODEL_PATH=/app/assets/yolov8n.onnx
    ports: ["9003:9003"]
    volumes:
      - ../../assets:/app/assets:ro
  results_adapter:
    build: ../../services/results_adapter
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    ports: ["9004:9004"]
    depends_on:
      - mosquitto
  ui:
    build: ../../ui/operator
    ports: ["5173:80"]
    depends_on:
      - results_adapter


